dist: xenial

language: python

cache: pip

python:
  - "3.6"

services:
  - docker

jobs:
  include:
    - stage: Tests
      script: bash scripts/test.sh

    - stage: Build image
      script: skip
      deploy:
        provider: script
        script: bash scripts/build.sh
