# Build Docker image and push to Docker Hub on merge to stage branch

name: Push Docker Image

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build & push Docker image
        run: |
          bash scripts/build-push.sh
        env:
          IMAGE_TAG: 0.0.1.build.${{ github.run_number }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
