# Test application and Docker container building

name: Build and Tests

on: [push, pull_request]

jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run pytest
        run: |
          bash scripts/test.sh

  buildImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          bash scripts/build.sh

  postNotification:
    runs-on: ubuntu-latest
    needs: [runTests, buildImage]
    if: always()
    steps:
      - name: Send success message to Slack
        if: needs.runTests.result == 'success' && needs.buildImage.result == 'success'
        uses: hbfernandes/slack-action@1.0
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: |
            {
              "channel": "C01667Y1K8U",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":bomb:Build *#${{ github.run_number }}* succeeded (<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Open>)"
                  }
                },
                {
                  "type": "divider"
                }
              ],
              "attachments": [
                {
                  "color": "#44bd32",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Actor* ${{ github.actor }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Repository* ${{ github.repository }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Commit* <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Status* OK"
                        }
                      ]
                    }
                  ]
                }
              ]
            }

      - name: Send fail message to Slack
        if: needs.runTests.result != 'success' || needs.buildImage.result != 'success'
        uses: hbfernandes/slack-action@1.0
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: |
            {
              "channel": "C01667Y1K8U",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":bomb:Build *#${{ github.run_number }}* failed (<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Open>)"
                  }
                },
                {
                  "type": "divider"
                }
              ],
              "attachments": [
                {
                  "color": "#c23616",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Actor* ${{ github.actor }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Repository* ${{ github.repository }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Commit* <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Status* Fail"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
